radiant-network/radiant-portal

- frontend/components/tsconfig.json
- frontend/components/types/assets-declaration.d.ts
- frontend/components/types/css-modules.d.ts
- frontend/components/vite.config.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/portals/radiant/app/types/assets-declaration.d.ts
- frontend/portals/radiant/tsconfig.json
- frontend/portals/radiant/vite.config.ts
remove typescript errors for dynamic `@assets` directory
> feat: fix typescript error for dynamic @assets

- frontend/README.md
- frontend/components/README.md
- frontend/components/components.json
- frontend/docs/code-conventions.md
- frontend/docs/contribution.md
- frontend/docs/development.md
- frontend/docs/project-structure.md
> updated documentation

- backend/internal/database/postgres.go
Inspired from other API and scripts using Postgres, we need to set that path if provided
> feat: CLIN-3377 add sslrootcert env

- frontend/Dockerfile.kf
- frontend/Dockerfile.radiant
- frontend/package-lock.json
- frontend/portals/radiant/tsconfig.json
Fix utils error on docker build
> fix: docker build

- backend/Dockerfile
- backend/Makefile
- backend/cmd/api/main.go
- backend/docker-compose.yml
- backend/go.mod
- backend/internal/database/postgres.go
- backend/scripts/init-sql/migrations/000001_init.up.sql
- backend/test/testutils/setup_postgres.go
> feat: CLIN-3377 - add DB migration

- backend/internal/database/postgres.go
Bien entendu ca fonctionne pas en QA :)
> feat: CLIN-3377 - migration after QA

- frontend/apps/variant/src/App.tsx
- frontend/components/base/Dialog/AlertDialogProvider.tsx
- frontend/components/base/Dialog/AlertDialogStore.ts
- frontend/components/base/ui/alert-dialog.tsx
- frontend/portals/radiant/app/root.tsx
- frontend/themes/kf/main.css
- frontend/themes/radiant/main.css
- frontend/themes/tailwind.base.config.js
Allow to open an alert dialog from anywhere with a func call:
```
import { alertDialog } from "@/components/base/Dialog/AlertDialogStore";
alertDialog.open({
type: "warning",
title: "...",
description: "...",
cancelProps: {
children: "Cancel",
},
actionProps: {
onClick: () => {},
children: "Save",
},
})
```
> ✨ Add AlertDialog Provider

- frontend/components/feature/QueryFilters/MultiSelect.tsx
- frontend/prettierrc.json
> fix: update prettierrc for consistency

- frontend/apps/variant/package.json
- frontend/apps/variant/src/App.tsx
- frontend/apps/variant/src/components/layouts/SidenavFilters.tsx
- frontend/components/base/Table/Table.tsx
- frontend/components/feature/QueryFilters/FilterList.tsx
- frontend/components/model/applications-config.tsx
- frontend/components/package.json
- frontend/docs/project-structure.md
- frontend/package-lock.json
- frontend/package.json
- frontend/portals/radiant/app/config/radiant.json
- frontend/portals/radiant/app/routes/home.tsx
- frontend/portals/radiant/config/kf.json
- frontend/portals/radiant/config/radiant.json
- frontend/portals/radiant/package.json
- frontend/portals/radiant/tsconfig.json
- frontend/portals/radiant/vite.config.ts
- Add configuration to define features and behavior of a portal
- provider to propagate the configuration
- useContext to access the configuration
- Update React workspace dependencies
- Some console cleanup
> feat: add portal configuration file

- frontend/apps/variant/src/App.tsx
- frontend/components/base/data-table/cells/external-link-cell.tsx
- frontend/components/base/data-table/cells/gene-cell.tsx
- frontend/components/base/data-table/cells/row-expand-cell.tsx
- frontend/components/base/data-table/data-table-column-settings.tsx
- frontend/components/base/data-table/data-table-index-result.tsx
- frontend/components/base/data-table/data-table-row-selection.tsx
- frontend/components/base/data-table/data-table-sortable-column-setting.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/hooks/use-resize-observer.tsx
- frontend/components/utils/number-format.ts
- DataTable should be able to manage server side pagination
https://github.com/user-attachments/assets/485fb7af-d1b3-49bf-9476-262b75d07cd4
> ✨ feat: SJRA-34 add server side pagination

- frontend/apps/variant/src/App.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/utils/number-format.ts
Add multi sorting for data-table
> ✨feat: SJRA-83 add multi-sorting for data-table

- frontend/apps/variant/src/App.tsx
- frontend/components/base/data-table/data-table-index-result.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/skeleton.tsx
https://github.com/user-attachments/assets/08caab63-4816-44d7-bfa4-9f4dce94abe6
> ✨feat: SJRA-86 add loadings state for table

- frontend/components/base/Buttons/ActionButton.tsx
- frontend/components/base/Buttons/IconButton.tsx
- frontend/components/base/Buttons/button.variants.ts
- frontend/components/base/ui/alert-dialog.tsx
- frontend/components/base/ui/button.tsx
- frontend/components/base/ui/pagination.tsx
- frontend/components/feature/QueryFilters/MultiSelect.tsx
- frontend/components/feature/query-builder/alerts.tsx
- frontend/components/feature/query-builder/query-bar/query-bar-delete-action.tsx
- frontend/components/feature/query-builder/query-bar/query-bar-save-dialog.tsx
- frontend/components/feature/query-builder/query-pill/query-pill-custom-edit-dialog.tsx
- frontend/components/feature/query-builder/query-toolbar/query-toolbar-add-action.tsx
- frontend/components/feature/query-builder/query-toolbar/query-toolbar-clear-action.tsx
- frontend/components/feature/query-builder/saved-filter/saved-filter-edit-dialog.tsx
- frontend/components/stories/base/buttons/action-button.stories.tsx
- frontend/components/stories/base/buttons/button.stories.tsx
- frontend/components/stories/base/buttons/icon-button.stories.tsx
- frontend/components/stories/base/buttons/utils.ts
- frontend/components/stories/base/overlays/alert.stories.tsx
- frontend/components/stories/base/overlays/tooltip.stories.tsx
- frontend/components/stories/feature/query-builder/query-builder.stories.tsx
- frontend/themes/radiant/main.css
> 💄 Improve button colors and variants

- frontend/apps/variant/src/App.tsx
- frontend/apps/variant/src/include_variant_table.tsx
- frontend/components/base/data-table/cells/clinvar-cell.tsx
- frontend/components/base/data-table/cells/empty-cell.tsx
- frontend/components/base/data-table/cells/external-link-cell.tsx
- frontend/components/base/data-table/cells/gene-cell.tsx
- frontend/components/base/data-table/cells/link-cell.tsx
- frontend/components/base/data-table/cells/mane-cell.tsx
- frontend/components/base/data-table/cells/number-cell.tsx
- frontend/components/base/data-table/cells/omim-cell.tsx
- frontend/components/base/data-table/cells/row-expand-cell.tsx
- frontend/components/base/data-table/cells/variant-class-cell.tsx
- frontend/components/base/data-table/cells/zygosity-cell.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/package-lock.json
See https://d3b.atlassian.net/browse/SJRA-93
> ✨feat: SJRA-93 add new columns to table

- frontend/apps/variant/package.json
- frontend/apps/variant/src/App.tsx
- frontend/components/base/Buttons/button.variants.ts
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/input-search.tsx
- frontend/components/base/list/list-item-with-action.tsx
- frontend/components/base/list/list.tsx
- frontend/components/base/multi-selector/multi-selector.tsx
- frontend/components/base/rich-text-editor/rich-text-editor.tsx
- frontend/components/base/ui/alert-dialog.tsx
- frontend/components/base/ui/badge.tsx
- frontend/components/base/ui/checkbox.tsx
- frontend/components/base/ui/dialog.tsx
- frontend/components/base/ui/input.tsx
- frontend/components/base/ui/select.tsx
- frontend/components/base/ui/switch.tsx
- frontend/components/base/ui/toggle.tsx
- frontend/components/feature/QueryFilters/MultiSelect.tsx
- frontend/components/feature/query-builder/query-builder.tsx
- frontend/components/stories/base/data-entry/input-search.stories.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/portals/radiant/package.json
- frontend/themes/radiant/main.css
- Input Search
- Fix dep
- Fix ui colors
> ✨ Input Search

- frontend/components/base/auto-complete.tsx
- frontend/components/base/multi-selector/multi-selector.tsx
- frontend/components/base/multi-selector/multi-selector.types.ts
- frontend/components/base/multi-selector/multi-selector.utils.tsx
- frontend/components/base/ui/command.tsx
- frontend/components/stories/base/data-entry/auto-complete.stories.tsx
- frontend/components/stories/base/data-entry/multi-selector.stories.tsx
Auto Complete: New
Multi Selector : Add check icon
> ✨ AutoComplete

- frontend/apps/variant/src/App.tsx
- frontend/components/base/data-table/cells/link-cell.tsx
- frontend/components/base/data-table/data-table-index-result.tsx
- frontend/components/base/icons/variant-icon.tsx
- frontend/components/feature/QueryFilters/FilterAccordion.tsx
- frontend/components/feature/QueryFilters/MultiSelect.tsx
- frontend/components/feature/query-builder/query-bar/query-bar-count.tsx
- frontend/components/feature/query-builder/query-builder.tsx
- frontend/components/feature/query-builder/query-toolbar/query-toolbar-combine-action.tsx
- frontend/components/feature/query-builder/types.ts
- frontend/components/lib/number-format.ts
- frontend/components/model/query-builder-core/query-builder-remote.ts
- frontend/components/model/query-builder-core/query-builder.ts
- frontend/components/model/query-builder-core/tests/query-builder.test.ts
- frontend/components/model/query-builder-core/utils/sqon.ts
- frontend/components/model/sqon.ts
- frontend/portals/radiant/app/root.tsx
> 🩹 Small fixes

- frontend/apps/variant/src/include_variant_table.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/hooks/use-resize-observer.tsx
- frontend/components/base/ui/table.tsx
- Improve performance for huge table
- Fix an issue where the size was just not working
https://github.com/user-attachments/assets/101a0d66-38d1-4782-9d08-09965d30a9b2
> ✨feat: SJIP-84 improve performance of column resizing

- frontend/apps/variant/src/App.tsx
- frontend/components/base/data-table/cells/clinvar-cell.tsx
- frontend/components/base/data-table/data-table-index-result.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/stories/base/data-display/data-table.stories.tsx
- Fix Results component (could overflow total)
- Fix pagination offset
- Reset pagination when needed
> 🐛fix: reset pagination on query change

- frontend/apps/variant/src/App.tsx
> ✨feat: SJIP-96 use page_index instead of offset

- frontend/apps/variant/src/feature/interpretation/mondo-auto-complete-form-field.tsx
- frontend/apps/variant/src/feature/interpretation/mondo-option-item-label.tsx
- frontend/components/base/data-entry/auto-complete.tsx
- frontend/components/base/ui/command.tsx
- frontend/components/stories/base/data-entry/auto-complete.stories.tsx
- frontend/portals/radiant/app/api/proxy.ts
- frontend/utils/api.ts
> ✨ Mondo autocomplete

- frontend/apps/variant/package.json
- frontend/components/base/icons/between-operator-icon.tsx
- frontend/components/base/typography/text-muted.tsx
- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/numerical-filter.tsx
- frontend/components/model/applications-config.tsx
- frontend/components/package.json
- frontend/components/stories/feature/query-filters/numerical-filter.stories.tsx
> feat: sjra-48 add numerical filter

- frontend/apps/variant/src/App.tsx
- frontend/apps/variant/src/feature/interpretation/hook.ts
- frontend/apps/variant/src/feature/interpretation/interpretation-dialog-button.tsx
- frontend/apps/variant/src/feature/interpretation/interpretation-form-generic.tsx
- frontend/apps/variant/src/feature/interpretation/interpretation-form-germline.tsx
- frontend/apps/variant/src/feature/interpretation/interpretation-form-somatic.tsx
- frontend/apps/variant/src/feature/interpretation/last-updated-banner.tsx
- frontend/apps/variant/src/feature/interpretation/mondo-auto-complete-form-field.tsx
- frontend/apps/variant/src/feature/interpretation/mondo-option-item-label.tsx
- frontend/apps/variant/src/feature/interpretation/pubmed-form-field.tsx
- frontend/apps/variant/src/feature/interpretation/types.ts
- frontend/components/base/data-entry/auto-complete.tsx
- frontend/components/base/data-entry/input-search.tsx
- frontend/components/base/data-entry/rich-text-editor/rich-text-editor.tsx
- frontend/components/base/ui/form.tsx
- frontend/components/stories/base/data-entry/auto-complete.stories.tsx
- frontend/package-lock.json
> ✨ Interpretation

- frontend/Dockerfile.kf
- frontend/Dockerfile.radiant
> fix: build with translation

- frontend/components/base/data-table/data-table.tsx
- frontend/components/feature/query-filters/numerical-filter.tsx
> fix: range filter interval

- frontend/translations/common/de.json
- frontend/translations/common/en.json
- frontend/translations/common/es.json
- frontend/translations/common/fr.json
> fix: add translations

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/components/feature/query-filters/use-aggregation-builder.ts
fix: optimized aggregation call hierarchy and prevent unnecessary calls
> fix: optimized aggregation call hierarchy and prevent unnecessary calls

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/components/feature/query-filters/numerical-filter.tsx
- frontend/translations/common/de.json
- frontend/translations/common/en.json
- frontend/translations/common/es.json
- frontend/translations/common/fr.json
> add notIn, someNotIn and All actions

- frontend/components/base/ui/accordion.tsx
- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/components/feature/query-filters/numerical-filter.tsx
> feat: add loading state for filters

- frontend/apps/variant/src/App.tsx
- frontend/apps/variant/src/feature/variant-table/table-settings.tsx
- frontend/components/base/data-table/cells/gene-cell.tsx
- frontend/components/base/data-table/data-table-row-selection.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
> ✨ Table theme

- frontend/components/base/back-link.tsx
- frontend/components/base/ui/breadcrumb.tsx
- frontend/components/stories/base/breadcrumb/back-link.stories.tsx
- frontend/components/stories/base/breadcrumb/breadcrumb.stories.tsx
- frontend/portals/radiant/tailwind.config.js
> ✨ Breadcrumb and back link components

- frontend/components/base/data-table/data-table.tsx
https://github.com/user-attachments/assets/e79667e6-0b2a-4bb7-9dba-2f02b8157d0a
> fix(table): SJIP-113 fix an issue where hidden a column will crash the table

- frontend/components/base/data-table/cells/gnomad-cell.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
- frontend/components/stories/base/data-display/data-table.stories.tsx
https://github.com/user-attachments/assets/e6143dbf-7f67-4e11-aeaa-9a2d0e71babb
> 💄 SJRA-116 sticky table column styling

- frontend/components/feature/query-builder/query-pill/query-pill-operator.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
> fix: query not in operator and

- .gitignore
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/translations/common/de.json
- frontend/translations/common/en.json
- frontend/translations/common/es.json
- frontend/translations/common/fr.json
> fix: SJRA-115 show more fix

- frontend/components/base/data-table/data-table.tsx
- frontend/portals/radiant/tailwind.config.js
prevent tailwind to look into node_modules.
Remove error in console about key not unique for tables.
> fix: tailwind optimisation table key fix

- frontend/components/base/ui/badge.tsx
- frontend/components/stories/base/data-display/badge.stories.tsx
- frontend/components/stories/base/data-display/utils.ts
> ✨ New badge variants

- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
Before:
https://github.com/user-attachments/assets/33d8f2b9-97ba-4cc8-b5c5-ae8e742f7cb8
After:
https://github.com/user-attachments/assets/4e6e9caa-b7c4-4b50-8fb0-a28a53c6391e
> ✨ Fix table expend scroll

- frontend/components/base/data-table/data-table.tsx
- frontend/translations/common/de.json
- frontend/translations/common/en.json
- frontend/translations/common/es.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/51375ea5-5f52-44ce-b3ca-fb5b46525ed2
> ✨feat(table): SJRA-130 add toggle full screen

- frontend/components/feature/navbar/main-navbar.tsx
- frontend/themes/common.css
some fix for scroll and dark mode
> fix: darkmode and scoll in menu

- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/translations/common/en.json
fix more -> More
5 items default
https://d3b.atlassian.net/browse/SJRA-117
> fix: sjra-122 fix show more number

- backend/go.mod
https://github.com/Ferlab-Ste-Justine/radiant-portal/security/dependabot/34
https://github.com/Ferlab-Ste-Justine/radiant-portal/security/dependabot/36
https://github.com/Ferlab-Ste-Justine/radiant-portal/security/dependabot/24
> fix: Fix dependabot alerts 24, 34 and 36

- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
> ✨feat(table): SJRA-141 change default padding

- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend-header.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/table-settings.tsx
- frontend/components/base/data-table/cells/pin-row-cell.tsx
- frontend/components/base/data-table/cells/row-expand-cell.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
> 🩹 Small ui fix

- frontend/components/base/data-table/data-table.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
- frontend/themes/tailwind.base.config.js
> ✨feat(cursor): SJRA-150 set cursor-default to use pointer, fix table storybook

- frontend/apps/variant-exploration/src/App.tsx
- frontend/apps/variant-exploration/src/feature/interpretation/interpretation-dialog-button.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/cells/interpretation-cell.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend-header.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/table-settings.tsx
- frontend/components/base/data-table/headers/table-tooltips-header.tsx
- frontend/components/base/icons/occurrence-icon.tsx
- frontend/components/feature/query-filters/sidebar-groups.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
- frontend/translations/portals/radiant/en.json
- frontend/translations/portals/radiant/fr.json
> ✨feat(occurrence): SJRA-133 add quick interpretation cell

- frontend/apps/variant-exploration/src/feature/occurrence-table/table-settings.tsx
> ✨feat(occurrence): SJRA-133 remove pinned action

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/filter-list.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
add some translation for some keys. otherwise use default backend value
> feat: srja-164 add keys for some filters

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/filter-list.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/7821e293-846c-46a0-8b0a-50765b5f4ec3
> ✨feat(filters): SJRA-163 add toggle expands button

- frontend/components/base/list/expandable-list.tsx
- frontend/components/stories/data-display/expandable-list.stories.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/77b8e098-ee7e-4cd2-ad43-1f79b8059a68
> ✨ Expandable list

- frontend/apps/variant-entity/src/App.tsx
- frontend/apps/variant-entity/src/components/overview/most-deleterious-consequence-card.tsx
- frontend/apps/variant-entity/src/components/overview/prediction-scores-card.tsx
- frontend/apps/variant-entity/src/components/transcripts-tab.tsx
- frontend/apps/variant-entity/src/components/transcripts/consequence-accordion-item.tsx
- frontend/apps/variant-entity/src/components/transcripts/transcript-details.tsx
- frontend/apps/variant-entity/src/components/transcripts/transcripts-tab.tsx
- frontend/components/base/ui/accordion.tsx
- frontend/components/feature/navbar/main-navbar.tsx
- frontend/components/feature/variant/impact-icon.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> ✨ SJRA-145 Transcripts first draft

- frontend/components/feature/query-filters/numerical-filter.tsx
- frontend/portals/radiant/config/kf.json
- frontend/portals/radiant/config/radiant.json
- frontend/translations/common/en.json
fix default operator for numerical range
> fix: sjra-185 fix default operator

- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend-header.tsx
> fix: sjra-168 typo litvar

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/filter-list.tsx
https://github.com/user-attachments/assets/c10e2650-57e5-43c9-88d3-a3d38daa6409
> 🐛fix(filter): SJIP-179 fix collapse button behavior

- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/hooks/use-table-localstorage.tsx
- Save column size
- Pinned row
https://github.com/user-attachments/assets/2cd7bb50-5476-4abe-b74f-3233417f11a2
> ✨feat(table): SJRA-187 save column size and pinned state

- frontend/apps/variant-exploration/src/feature/occurrence-table/table-settings.tsx
- frontend/components/base/data-table/cells/pin-row-cell.tsx
> ✨feat(table): SJRA-187 remove row pinning feature

- frontend/components/base/data-table/data-table-column-settings.tsx
- frontend/components/base/data-table/data-table.tsx
https://github.com/user-attachments/assets/d1a8cd99-3101-46fa-9e1b-052dab7b45fa
> ✨feat(table): SJRA-208 hide pinned column in column settings

- frontend/apps/variant-entity/src/App.tsx
- frontend/apps/variant-entity/src/components/transcripts/consequence-accordion-item.tsx
- frontend/components/base/result.tsx
- frontend/components/base/ui/accordion.tsx
- frontend/components/stories/feedback/result.stories.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
Nouveau component Result -> similaire à AntDesign:
> ✨ Small fix + add result component

- frontend/components/base/data-table/data-table-column-settings.tsx
- frontend/components/base/data-table/data-table-column-visibility-settings.tsx
- frontend/components/base/data-table/data-table-sortable-column-setting.tsx
> ✨feat(table): SJRA-208 disable dnd for pinned columns

- frontend/apps/variant-exploration/src/feature/occurrence-table/table-settings.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/hooks/use-table-localstorage.tsx
https://github.com/user-attachments/assets/0b6c1f9f-eeb1-4de3-ac34-62cee8dd079e
> 🐛fix(table): SJRA-216 improve resize loading

- frontend/apps/variant-exploration/src/App.tsx
> 🐛fix(sidebar): SJRA-217 fix scroll behavior

- frontend/apps/variant-entity/src/components/overview/most-deleterious-consequence-card.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/cells/most-deleterious-consequence-cell.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend-transcript.tsx
- frontend/components/feature/variant/consequence-label.tsx
- frontend/components/stories/feature/variant/consequence-label.stories.tsx
> ✨ Consequence component

- frontend/portals/radiant/config/kf.json
- frontend/portals/radiant/config/radiant.json
> fix: sjra-232 add consequence to filters

- frontend/apps/variant-exploration/src/feature/interpretation/data.ts
- frontend/apps/variant-exploration/src/feature/interpretation/interpretation-dialog.tsx
- frontend/apps/variant-exploration/src/feature/interpretation/interpretation-form-germline.tsx
- frontend/apps/variant-exploration/src/feature/interpretation/interpretation-form-somatic.tsx
- frontend/apps/variant-exploration/src/feature/interpretation/occurence-details.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/cells/clinvar-cell.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/classification-section.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/clinical-association-section.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/detail-section.tsx
- frontend/components/feature/variant/clinvar-badge.tsx
> ✨ Add occurrence details to interpretation modal

- frontend/apps/variant-entity/src/App.tsx
- frontend/apps/variant-entity/src/components/cases-tab.tsx
- frontend/apps/variant-entity/src/components/cases/cases-filters.tsx
- frontend/apps/variant-entity/src/components/cases/cases-mondo-autocomplete.tsx
- frontend/apps/variant-entity/src/components/cases/cases-tab.tsx
- frontend/apps/variant-entity/src/components/cases/interpreted-cases-table.tsx
- frontend/apps/variant-entity/src/components/cases/other-cases-table.tsx
- frontend/apps/variant-entity/src/components/cases/table-settings.tsx
- frontend/apps/variant-exploration/src/feature/interpretation/mondo-auto-complete-form-field.tsx
- frontend/components/base/data-entry/auto-complete.tsx
- frontend/components/base/data-table/data-table-header-actions.tsx
- frontend/components/base/data-table/data-table-skeleton-loading.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/command.tsx
- frontend/components/base/ui/input.tsx
- frontend/components/feature/variant/mondo-option-item-label.tsx
- frontend/components/stories/data-entry/input.stories.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> ✨ SJRA-144 variant entity cases first draft

- frontend/apps/variant-exploration/src/feature/occurrence-table/clinical-association-section.tsx
> fix: sjra-232

- frontend/apps/variant-exploration/src/feature/occurrence-table/clinical-association-section.tsx
> fix: sjra-232 fix error

- frontend/apps/variant-exploration/src/feature/occurrence-table/frequency-section.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend-transcript.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> fix: sjra-232 RQDM tooltip, icon and typo

- frontend/components/.storybook/preview.tsx
- frontend/components/base/data-entry/editable-text.tsx
- frontend/components/base/data-table/data-table-header-actions.tsx
- frontend/components/base/list/list-item-with-action.tsx
- frontend/components/base/ui/select.tsx
- frontend/components/feature/query-builder/alerts.tsx
- frontend/components/feature/query-builder/query-pill/query-pill-combiner.tsx
- frontend/components/feature/query-builder/query-pill/query-pill-custom-edit-dialog.tsx
- frontend/components/feature/query-builder/query-pill/query-pill-custom.tsx
- frontend/components/feature/query-builder/saved-filter/saved-filter-manage-dialog.tsx
- frontend/components/feature/query-builder/saved-filter/saved-filter-save-action.tsx
- frontend/components/feature/query-builder/saved-filter/saved-filter-select.tsx
- frontend/components/feature/query-filters/custom-pill-filter.tsx
- frontend/components/feature/query-filters/toggle-filter.tsx
- frontend/components/model/query-builder-core/query-builder.ts
- frontend/components/model/query-builder-core/saved-filter.ts
- frontend/components/model/query-builder-core/tests/saved-filter.test.ts
- frontend/components/stories/data-display/expandable-list.stories.tsx
- frontend/components/stories/data-display/list-item-with-action.stories.tsx
- frontend/components/stories/feature/query-builder/query-builder.stories.tsx
- frontend/components/stories/feature/query-builder/utils.ts
- frontend/components/stories/feature/query-filters/custom-pill-filter.stories.tsx
- frontend/portals/radiant/app/utils/auth.server.ts
- frontend/themes/common.css
- frontend/themes/tailwind.base.config.js
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/61d36c4d-60ed-4d16-abe0-f5866d42c824
> ✨ SJRA-260 custom pill filter

- frontend/apps/variant-exploration/src/feature/occurrence-table/metric-section.tsx
> fix: sjra-250 genotype quality icon update

- frontend/apps/variant-exploration/src/feature/occurrence-table/cells/clinvar-cell.tsx
- frontend/components/feature/theme-toggle/theme-provider.tsx
- frontend/package-lock.json
- frontend/package.json
Note: Une tâche sera créer afin de faire un rendu SSR du theme
https://github.com/user-attachments/assets/ce2de7f9-17c4-4a7f-a417-da8c678e27e0
> feat(theme): SJRA-224 use cookie to load theme

- frontend/components/base/empty.tsx
- frontend/components/stories/feedback/empty.stories.tsx
> ✨ Empty Component Update

- frontend/apps/variant-entity/src/App.tsx
- frontend/apps/variant-entity/src/components/cases/table-settings.tsx
- frontend/apps/variant-entity/src/components/evidence-tab.tsx
- frontend/apps/variant-entity/src/components/evidence/clinVar-card.tsx
- frontend/apps/variant-entity/src/components/evidence/condition-phenotype-card.tsx
- frontend/apps/variant-entity/src/components/evidence/evidence-tab.tsx
- frontend/apps/variant-entity/src/components/evidence/gene-accordion-item.tsx
- frontend/apps/variant-entity/src/components/evidence/table-settings.tsx
- frontend/apps/variant-entity/src/components/overview/associated-conditions-card.tsx
- frontend/apps/variant-entity/src/components/overview/external-references-card.tsx
- frontend/apps/variant-entity/src/components/overview/most-deleterious-consequence-card.tsx
- frontend/apps/variant-entity/src/components/overview/my-organization-card.tsx
- frontend/apps/variant-entity/src/components/overview/overview-tab.tsx
- frontend/apps/variant-entity/src/components/overview/prediction-scores-card.tsx
- frontend/apps/variant-entity/src/components/transcripts/consequence-accordion-item.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/occurrence-expend.tsx
- frontend/components/base/empty.tsx
- frontend/components/base/number-badge.tsx
- frontend/components/base/ui/button.tsx
- frontend/components/base/ui/card.tsx
- frontend/components/base/ui/tabs.tsx
- frontend/components/feature/navbar/main-navbar-button.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
- frontend/components/stories/data-display/number-badge.stories.tsx
- frontend/components/stories/data-display/utils.ts
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> ✨ SJRA-282 Variant Entity Evidence and condition shell

- frontend/apps/variant-entity/src/components/overview/prediction-scores-card.tsx
- frontend/apps/variant-entity/src/components/transcripts/consequence-accordion-item.tsx
- frontend/apps/variant-entity/src/components/transcripts/transcript-details.tsx
- frontend/components/base/list/expandable-list.tsx
> feat(prediction): SJRA-279 shift order of prediction scores

- frontend/apps/variant-exploration/src/feature/occurrence-table/clinical-association-section.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/prediction-section.tsx
- frontend/apps/variant-exploration/src/feature/occurrence-table/zygosity-section.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://d3b.atlassian.net/browse/SJRA-284
> fix: sjra-284 occurence enhancement

- frontend/portals/radiant/config/radiant.json
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> fix: sjra-280

- frontend/components/feature/query-filters/filter-container.tsx
> fix: sjra-261

- frontend/components/base/ui/checkbox.tsx
- frontend/components/base/ui/command.tsx
- frontend/components/stories/data-entry/command.stories.tsx
figma: https://www.figma.com/design/Y0l9SoMCYlTQZxce3NzZiK/shadcn_ui-kit-for-Figma---Pro-Blocks---New-York---January-2025?node-id=18541-793&m=dev&focus-id=18541-776
> feat(command): SJRA-299 add CommandItemCheckbox

- frontend/apps/case-exploration/src/App.tsx
- frontend/apps/case-exploration/src/components/cases/cases-tab.tsx
- frontend/apps/case-exploration/src/components/filters-group/filters-group.tsx
- frontend/apps/case-exploration/src/feature/case-table/table-settings.tsx
- frontend/apps/variant-exploration/src/App.tsx
- frontend/components/base/data-table/data-table-column-settings.tsx
- frontend/components/base/data-table/data-table-fullscreen-button.tsx
- frontend/components/base/data-table/data-table-header-actions.tsx
- frontend/components/base/data-table/data-table-skeleton-loading.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/filters-group/filters-group-skeleton.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
- frontend/utils/api.ts
> feat(case): SJRA-152 add basic table infrastructure

- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/filters-group/filters-group-skeleton.tsx
> fix(filters-table): SJRA-000 fix skeletons loading alignment

- frontend/apps/case-exploration/src/components/cases/cases-tab.tsx
- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
- frontend/apps/case-exploration/src/components/table-filters/table-filters.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
add search to cases
https://github.com/user-attachments/assets/8daf53b2-8f63-4faa-9c9e-b3a8ea674061
> feat: sjra-151

- frontend/apps/case-exploration/src/feature/cells/analysis-type-code-cell.tsx
- frontend/components/base/ui/badge.tsx
- frontend/components/stories/data-display/badge.stories.tsx
> ✨ Badge icon only variant

- frontend/components/base/navigation/tabs-nav/tabs-nav.tsx
- frontend/components/stories/navigation/tabs-nav.stories.tsx
> ✨ Add icon support for tabs nav

- frontend/apps/case-exploration/src/App.tsx
- frontend/apps/case-exploration/src/components/table-filters/filter-item-status.ts
- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
- frontend/apps/case-exploration/src/components/table-filters/table-filters.tsx
- frontend/components/base/buttons/filter-button.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
multiple fix:
Correctifs
- “Placeholder” de “More” ne suit pas la même logique que les autres buttons. Affiché 'filters'
- ouvrir un panneau de filtre ajouté dynamiquement
- Retirer le button Clear pour More
- Retirer les Filtres de ‘More’ lorsque affiché
- table full width
https://github.com/user-attachments/assets/dcd78275-9812-489b-80bf-0a3a450dae27
> fix: sjra-153 fix more filter behavior

- frontend/components/base/data-table/data-table-header-actions.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/ui/table.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
- frontend/themes/kf/theme.css
- frontend/themes/radiant/theme.css
- frontend/themes/tailwind.base.css
DO NOT MERGE YET, need to talk to lucas about header bg color which currently has an opacity and that doesnt work with pinned row (we see the column in the background when hovered)
https://github.com/user-attachments/assets/94a569f8-a10b-4d2d-8324-25d521030214
> ✨ Update DataTable header

- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
fix multiple highlights in search component
> fix: sjra-153 multiple selection

- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
Fix accordion text to match design
Fix checkbox position on multiline filter
fix count label to match design
Fix count label on multiline
fix search
> fix: sjra-312 UI to match design

- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
fix https://d3b.atlassian.net/browse/SJRA-375
sanitize value before being use for api search
> fix: sjra-275 sanitize value for proper query

- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
- frontend/components/base/buttons/filter-button.tsx
- frontend/components/base/ui/command.tsx
The command ui update has cause some regression. 
- in interpretation form
- in case filter
- in case auto complete
https://d3b.atlassian.net/browse/SJRA-381
> fix: sjra-381 fix command component regression

- frontend/components/hooks/I18nProvider.tsx
- frontend/components/hooks/i18n.server.ts
- frontend/components/hooks/i18n.ts
- frontend/portals/radiant/app/root.tsx
add translation keys to the server side render to prevent having only the keys on first load.
> fix: sjra-266 lazy load translation

- frontend/apps/case-entity/README.md
- frontend/apps/case-entity/index.html
- frontend/apps/case-entity/package.json
- frontend/apps/case-entity/postcss.config.cjs
- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-entity/src/components/details/details-tab.tsx
- frontend/apps/case-entity/src/components/details/patient-information-card.tsx
- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/apps/case-entity/src/main.tsx
- frontend/apps/case-entity/src/types.ts
- frontend/apps/case-entity/src/vite-env.d.ts
- frontend/apps/case-entity/tsconfig.app.json
- frontend/apps/case-entity/tsconfig.json
- frontend/apps/case-entity/tsconfig.node.json
- frontend/apps/case-entity/vite.config.mts
- frontend/apps/case-exploration/src/feature/case-table/table-settings.tsx
- frontend/portals/radiant/app/routes.ts
- frontend/portals/radiant/app/routes/cases/entity.tsx
- frontend/portals/radiant/tsconfig.json
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat: sjra-401 case entity header

- frontend/components/feature/query-filters/numerical-filter.tsx
- frontend/components/model/query-builder-core/query-builder-remote.ts
https://github.com/user-attachments/assets/3e34f8f9-922b-40ec-9127-9ef692bd6b66
> fix(numerical): SJRA-385 add clear function

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/layout/header.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> fix: sjra-401 add icons and pixel perfect

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/variant-entity/src/App.tsx
- frontend/components/base/container.tsx
> fix: sjra-411 max width

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-entity/src/components/details/details-tab.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat: sjra-233 case details

- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/components/feature/query-filters/use-aggregation-builder.ts
> fix(aggregate): SJRA-400 update seq_id for aggregate

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-entity/src/components/details/clinical-card.tsx
- frontend/apps/case-entity/src/components/details/details-tab.tsx
- frontend/apps/case-entity/src/components/details/patient-information-card.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat: sjra-421 patient information

- frontend/apps/case-entity/src/components/layout/header.tsx
- frontend/apps/variant-entity/src/App.tsx
- frontend/components/base/headers/page-header.tsx
- frontend/components/stories/data-display/page-header.stories.tsx
> feat(entity): SJRA-416 add entity-header-component

- frontend/portals/radiant/public/radiant/site.webmanifest
fix manifest for android (file not found)
> fix: sjra-432 fix manifest

- frontend/components/base/data-table/data-table.tsx
> fix(table): SJRA-433 fix empty state display

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat: SJRA-392 update table to use case tasks data

- frontend/themes/tailwind.base.css
ajout du pointeur pour les clicks
> fix: sjra-405

- frontend/components/base/information/information-field.tsx
> fix: sjra-405 refactor double ternary

- frontend/apps/case-entity/src/components/details/clinical-card.tsx
> fix(clinical): SJRA-417 fix phenotypes display

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
> fix: sjra-452 priority colors

- frontend/apps/case-exploration/src/feature/cells/case-actions-menu-cell.tsx
- frontend/apps/case-exploration/src/feature/cells/priority-cell.tsx
- frontend/components/base/information/empty-field.tsx
- frontend/components/base/information/information-field.tsx
> fix(action): SJRA-438 disable view variants on list, add emptyfield

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-entity/src/components/details/details-tab.tsx
- frontend/apps/case-entity/src/components/details/patient-information-card.tsx
> fix: sjra-431 responsive update

- frontend/apps/case-exploration/src/components/table-filters/table-filters-search.tsx
> fix: sjra-153 command input focus missing style

- frontend/apps/case-entity/src/components/variants/occurrence-table/gene-section.tsx
> fix(interpretation): SJRA-354 fix spliceIA link

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-exploration/src/components/table-filters/filter-item-priority.tsx
- frontend/apps/case-exploration/src/components/table-filters/table-filters.tsx
- frontend/components/base/buttons/filter-button.tsx
- frontend/components/base/ui/indicator.tsx
> fix: sjra-466 focus visibility case search

- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
https://github.com/user-attachments/assets/61a72632-604c-4d10-9bcf-e9277684ffaa
> fix(variant): SJRA-455 fix pagination and sorting

- frontend/apps/case-entity/src/components/details/clinical-card.tsx
- frontend/components/base/ui/collapsible.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(clinical): SJRA-458 add CollapsibleList component

- frontend/components/types/assets-declaration.d.ts
- frontend/portals/radiant/vite.config.mts
language loading error
this remove all theme translation to only import the translation file for the project. Previously kf files were also included.
> fix: sjra-266 translations

- frontend/.gitignore
- frontend/components/hooks/i18n.server.ts
- frontend/components/hooks/i18n.ts
- frontend/components/types/assets-declaration.d.ts
- frontend/portals/radiant/merge-translations.ts
- frontend/portals/radiant/vite.config.mts
merge translation file in one before bundle. Optimize load and risk a server/client variation.
> fix: sjra-266 merge translation files before build optimization

- frontend/apps/case-exploration/src/feature/cells/priority-cell.tsx
> fix(priority): SJRA-404 tooltip should expand correctly

- frontend/apps/case-entity/src/components/variants/interpretation/transcript.tsx
- frontend/apps/case-entity/src/components/variants/occurrence-table/occurrence-expand-transcript.tsx
- frontend/apps/variant-entity/src/components/cases/interpreted-cases-expand.tsx
- frontend/apps/variant-entity/src/components/overview/external-references-card.tsx
- frontend/apps/variant-entity/src/components/overview/most-deleterious-consequence-card.tsx
- frontend/components/feature/variant/transcript-id-link.tsx
- frontend/components/feature/variant/utils.ts
> fix: SJRA-472 fix expand occurrence header and remove hardcoded value

- frontend/apps/case-entity/src/components/details/clinical-card.tsx
- frontend/components/base/list/expandable-list.tsx
- frontend/components/base/ui/collapsible.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(list): SJRA-000 re-use expandableList component

- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
> fix(variant): SJRA-304 remove variant title

- frontend/apps/case-entity/src/components/details/assay-informations-card.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/stories/data-display/data-table.stories.tsx
> fix(table): SJRA-447 always display pagination

- frontend/apps/case-entity/src/components/variants/occurrence-table/table-settings.tsx
- frontend/apps/case-entity/src/feature/cells/actions-menu-cell.tsx
- frontend/apps/case-exploration/src/feature/case-table/table-settings.tsx
- frontend/apps/case-exploration/src/feature/cells/case-actions-menu-cell.tsx
- frontend/apps/variant-entity/src/components/cases/table-settings.tsx
- frontend/apps/variant-entity/src/components/evidence/clinVar-card.tsx
- frontend/apps/variant-entity/src/components/evidence/condition-phenotype-card.tsx
- frontend/apps/variant-entity/src/components/evidence/gene-accordion-item.tsx
- frontend/apps/variant-entity/src/components/evidence/table-settings.tsx
- frontend/apps/variant-entity/src/components/overview/most-deleterious-consequence-card.tsx
- frontend/apps/variant-entity/src/components/transcripts/transcripts-tab.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/hooks/use-table-localstorage.tsx
- frontend/components/base/empty.tsx
- frontend/components/base/number-badge.tsx
- frontend/components/base/ui/badge.tsx
- frontend/components/feature/variant/clinvar-badge.tsx
- frontend/components/stories/data-display/badge.stories.tsx
- frontend/themes/radiant/theme.css
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
- Update to variant Entity
- Include Badge Variant
- Other fixes
> SJRA-282 evidence

- frontend/components/base/data-table/data-table.tsx
https://github.com/user-attachments/assets/da2af6e5-50a2-4651-9798-d63996766bae
> fix(table): SJRA-467 fix fullscreen in dark mode

- backend/internal/repository/gene_panels.go
- backend/scripts/init-sql/init_starrocks.sql
- backend/test/data/gene_panels/orphanet_gene_panel.tsv
- backend/test/data/sql/orphanet_gene_panel.sql
For orphanet gene panel, use inheritance code to get a nornalized value for inheritance column
> :sparkles: feat: SJRA-348 use inheritance_code column in orphanet panel

- frontend/apps/case-entity/src/components/details/patient-information-card.tsx
- frontend/portals/radiant/merge-translations.ts
- frontend/translations/common/fr.json
fix dev reload translation
update patient information
> fix: sjra-421 patient info label

- frontend/apps/case-entity/src/components/details/patient-information-card.tsx
- frontend/components/base/information/information-field.tsx
> fix: sjra-421 change cursor pointer

- frontend/components/base/ui/card.tsx
> fix(card): SJRA-481 adjust padding on mobile display

- frontend/apps/variant-entity/src/components/transcripts/transcript-details.tsx
> fix(variant): SJRA-484 remove duplicate aa_change

- frontend/components/base/data-table/data-table-header-actions.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> fix(table): SJRA-507 fix icon, force display when enabled

- frontend/components/.storybook/i18n.ts
- frontend/components/.storybook/preview.tsx
> fix: sjra-515 translation in storybook

- frontend/components/base/ui/tooltip.tsx
- frontend/components/stories/feedback/tooltip.stories.tsx
> fix(tooltip): SJRA-517 add max width

- frontend/components/base/buttons/filter-button.tsx
https://github.com/user-attachments/assets/45b3c19a-ad4f-448b-83cb-5f61a3b35b03
> fix: sjra-528 case list filter update

- backend/internal/repository/assays.go
- backend/internal/repository/cases.go
- backend/internal/repository/clinvar_rcv.go
- backend/internal/repository/exomiser.go
- backend/internal/repository/gene_panels.go
- backend/internal/repository/occurrences.go
- backend/internal/repository/sequencing.go
- backend/internal/repository/starrocks_repository.go
- backend/internal/repository/terms.go
- backend/internal/repository/variants.go
Was changed 2 months ago to `Fatal` QLIN doesn't have Starrock.
> fix: CLIN-4877 - revert fatal logs

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/apps/case-entity/src/feature/cells/actions-menu-cell.tsx
https://github.com/user-attachments/assets/752b6340-2091-4cea-b7dc-9694b2fc1e64
> feat(assay): SJRA-524 use queryParams to manage seq_id selection

- frontend/apps/case-entity/src/components/details/details-tab.tsx
- frontend/apps/variant-entity/src/App.tsx
- frontend/apps/variant-entity/src/components/cases/cases-tab.tsx
- frontend/apps/variant-entity/src/components/evidence/evidence-tab.tsx
- frontend/apps/variant-entity/src/components/overview/overview-tab.tsx
- frontend/apps/variant-entity/src/style.ts
> App container to variant entity

- frontend/components/feature/query-filters/numerical-filter.tsx
fix default query always query default values that are not needed and it create duplicates query each time.
> fix: sjra-532 multiple statistic query

- frontend/apps/case-exploration/src/components/table-filters/table-filters.tsx
- frontend/components/base/buttons/filter-button.tsx
fix 
https://d3b.atlassian.net/browse/SJRA-551 
https://d3b.atlassian.net/browse/SJRA-550
please merge if approve
> fix: sjra-550

- frontend/apps/case-entity/src/components/details/bioinformatics-section.tsx
- frontend/components/base/cards/collapsible-card.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/display-table.tsx
- frontend/components/base/modals/upload-id-modal.tsx
- frontend/components/base/ui/card.tsx
- frontend/components/base/ui/table.tsx
- frontend/components/stories/cards/collapsible-card.stories.tsx
- frontend/components/stories/collapsibles/collapsible.stories.tsx
- frontend/components/stories/modals/upload-id-modal.stories.tsx
- frontend/components/stories/table/cells-mock.tsx
- frontend/components/stories/table/data-table.stories.tsx
- frontend/components/stories/table/display-table.stories.tsx
- frontend/components/stories/table/table-mock.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(modal): SJRA-70 add upload-id modal

- frontend/apps/case-entity/src/components/details/clinical-card.tsx
- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/apps/case-exploration/src/feature/cells/case-actions-menu-cell.tsx
https://github.com/user-attachments/assets/d679b247-729d-44d6-9ff8-30333ba4c9f6
> feat(case): SJRA-449 add view variants to case list

- frontend/apps/case-entity/src/components/variants/filters/assay-variant-filters.tsx
- frontend/components/base/ui/select.tsx
> fix(dropdown): SJRA-575 fix pagination icon color

- frontend/docs/create-an-application.md
- frontend/portals/radiant/app/layout/protected-layout.tsx
- frontend/portals/radiant/app/routes.ts
> feat(route): SJRA-600 use case instead of case-exploration

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/variants/interpretation/interpretation-dialog.tsx
- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/apps/case-exploration/src/App.tsx
- frontend/cli/create-application/template/src/App.tsx
> style(theme): SJRA-486 improve background constrast

- frontend/apps/variant-entity/src/components/cases/interpreted-cases-expand.tsx
- frontend/apps/variant-entity/src/components/cases/table-settings.tsx
- frontend/apps/variant-entity/src/components/evidence/evidence-tab.tsx
- frontend/components/base/navigation/phenotypes/phenotype-condition-link.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
Fix all Inprogress bugs in https://d3b.atlassian.net/browse/SJRA-92
> Couple fixes

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(case): SJRA-541 add project code

- frontend/components/base/checkboxes/checkbox-filter.tsx
- frontend/components/base/ui/checkbox.tsx
- frontend/components/base/ui/label.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/components/stories/inputs/checkbox-filter.stories.tsx
- frontend/components/stories/inputs/checkbox.stories.tsx
> feat(input): SJRA-628 add new checkbox filter component

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/details/clinical-card.tsx
- frontend/apps/case-entity/src/components/variants/variants-tab.tsx
- frontend/apps/case-entity/src/main.tsx
- frontend/apps/case-exploration/src/components/cases/cases-tab.tsx
- frontend/apps/case-exploration/src/feature/case-table/table-settings.tsx
- frontend/portals/radiant/app/layout/protected-layout.tsx
- frontend/portals/radiant/app/root.tsx
- frontend/portals/radiant/app/routes/home.tsx
https://github.com/user-attachments/assets/4e9be326-314b-472b-928b-fba0274a0e49
> fix(case): SJRA-637 reset scroll position on case-entity

- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/display-table.tsx
- frontend/components/stories/table/data-table.stories.tsx
> feat(table): SJRA-641 fix header groups

- frontend/components/base/data-table/data-table-fullscreen-button.tsx
- frontend/components/base/data-table/data-table-group-by.tsx
- frontend/components/base/data-table/data-table.tsx
> fix(table): SJRA-376 adjust group by icon

- frontend/components/base/data-table/data-table-column-settings.tsx
- frontend/components/base/data-table/data-table-group-by.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/2a1c03c7-acb2-4569-8fca-33bdc07c9cd9
> fix(table): SJRA-646 update tooltips

- frontend/.husky/commit-msg
- frontend/.husky/pre-commit
- frontend/commitlint.config.cjs
- frontend/components/base/data-table/data-table.tsx
- frontend/package-lock.json
- frontend/package.json
> chore(husky): SJRA-638 add husky hooks"

- frontend/components/base/buttons/button.variants.ts
> fix(button): SJRA-652 fix icon only size

- frontend/apps/case-entity/src/App.tsx
- frontend/docs/onboarding.md
- frontend/package-lock.json
[SJRA-642](https://d3b.atlassian.net/browse/SJRA-642)
Tabs should be align with title.
[SJRA-642]: https://d3b.atlassian.net/browse/SJRA-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(case): SJRA-642 tabs style

- frontend/.eslintrc.cjs
- frontend/components/.storybook/main.ts
- frontend/components/.storybook/preview.tsx
- frontend/components/base/checkboxes/checkbox-filter.tsx
- frontend/components/base/typography/text-muted.tsx
- frontend/components/base/ui/card.tsx
- frontend/components/base/ui/input.tsx
- frontend/components/base/ui/select.tsx
- frontend/components/base/ui/table.tsx
- frontend/components/feature/query-filters/filter-container.tsx
- frontend/components/feature/query-filters/filter-list.tsx
- frontend/components/feature/query-filters/multiselect-filter.tsx
- frontend/components/feature/query-filters/numerical-filter.tsx
- frontend/components/package-lock.json
- frontend/components/package.json
- frontend/components/stories/badges/affected-status-badge.stories.tsx
- frontend/components/stories/facets/filter-list.stories.tsx
- frontend/components/stories/public/api-occurence.tsx
- frontend/components/stories/public/mockServiceWorker.js
- frontend/package-lock.json
- frontend/themes/tailwind.base.css
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(facet): SJRA-651 add new facet design

- frontend/apps/case-entity/src/App.tsx
- frontend/apps/case-entity/src/components/files/files-tab.tsx
- frontend/apps/case-entity/src/components/files/files-table/files-table-filters.tsx
- frontend/apps/case-entity/src/components/files/files-table/table-settings.tsx
- frontend/apps/case-entity/src/types.ts
- frontend/components/base/data-table/cells/badge-cell.tsx
- frontend/components/base/data-table/cells/date-cell.tsx
- frontend/components/base/data-table/cells/document-size-cell.tsx
- frontend/components/base/data-table/cells/gene-cell.tsx
- frontend/components/base/data-table/cells/relationship-to-proband-cell.tsx
- frontend/components/base/data-table/cells/text-cell.tsx
- frontend/components/base/data-table/data-table-skeleton-loading.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/information/document-size.tsx
- frontend/components/base/information/empty-field.tsx
- frontend/components/base/information/relationship-to-proband-field.tsx
- frontend/components/package-lock.json
- frontend/components/package.json
- frontend/components/stories/informations/document-size.stories.tsx
- frontend/components/stories/informations/information-field.stories.tsx
- frontend/components/stories/informations/relationship-to-proband-field.stories.tsx
- frontend/components/stories/table/cells-mock.tsx
- frontend/package-lock.json
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(case): SJRA-582 add files tab

- backend/cmd/api/cases_integration_test.go
- backend/cmd/api/documents_integration_test.go
- backend/internal/repository/documents_test.go
- backend/scripts/init-sql/migrations/000015_add_sibling_relationship_code.down.sql
- backend/scripts/init-sql/migrations/000015_add_sibling_relationship_code.up.sql
- backend/scripts/init-sql/migrations/000016_change_name_en_rna_dna.down.sql
- backend/scripts/init-sql/migrations/000016_change_name_en_rna_dna.up.sql
- SJRA-630 add sibling relationship code
- SJRA-450 rename sample_type name_en
> feat: SJRA-630 add sibling relationship code

- frontend/apps/file-exploration/src/components/files-archive-list.tsx
- frontend/components/base/data-table/data-table.tsx
- frontend/components/base/data-table/filters/data-table-filter-search.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
https://github.com/user-attachments/assets/0d862c3e-bb42-48f6-bdd8-06f731192431
> fix(file): SJRA-625 change default sorting and fix translations

- frontend/apps/variant-entity/src/components/transcripts/consequence-accordion-item.tsx
> fix(transcript): SJRA-556 adjust accordion with card

- frontend/apps/case-entity/src/components/files/files-table/files-tab-table-settings.tsx
> fix(case): SJRA-695 fix typo

- frontend/apps/case-entity/src/components/details/analysis-card.tsx
- frontend/apps/case-entity/src/components/files/files-table/files-table-filters.tsx
- frontend/apps/case-exploration/src/components/cases/cases-tab.tsx
- frontend/apps/case-exploration/src/components/table-filters/case-exploration-table-filters.tsx
- frontend/apps/file-exploration/src/components/files-archive-list-table-filters.tsx
- frontend/components/base/data-table/filters/data-table-filter-search.tsx
- frontend/components/base/data-table/filters/data-table-filters.tsx
- frontend/components/base/data-table/filters/options/option-data-type.tsx
- frontend/components/base/data-table/filters/options/option-file-format.tsx
- frontend/components/base/data-table/filters/options/option-priority.tsx
- frontend/components/base/data-table/filters/options/option-status.tsx
- frontend/components/stories/table/data-table-filters.stories.tsx
- frontend/components/stories/table/data-table.stories.tsx
> fix(filter): SJRA-696 add global option filter

- frontend/components/base/information/relationship-to-proband-field.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> fix(relationship): SJRA-686 keep raw relationship data

- frontend/apps/case-entity/src/components/files/files-table/files-table-filters.tsx
- frontend/apps/case-exploration/src/components/table-filters/case-exploration-table-filters.tsx
- frontend/apps/file-exploration/src/components/files-archive-list-table-filters.tsx
- frontend/components/base/data-table/filters/data-table-filter-search.tsx
- frontend/components/base/data-table/filters/data-table-filters.tsx
https://github.com/user-attachments/assets/1903e9f9-6673-47c3-ad04-33e3ab52882f
> fix(filter): SJRA-701 improve filters config

- frontend/apps/case-entity/src/components/files/files-table/files-tab-table-settings.tsx
- frontend/apps/case-entity/src/components/variants/occurrence-table/occurence-table-settings.tsx
- frontend/apps/case-entity/src/feature/assays-table/table-settings.tsx
- frontend/apps/case-exploration/src/feature/case-table/table-settings.tsx
- frontend/apps/file-exploration/src/components/files-archive-table-settings.tsx
- frontend/apps/variant-entity/src/components/cases/table-settings.tsx
- frontend/components/base/data-table/cells/anchor-link-cell.tsx
- frontend/components/base/data-table/cells/condition-cell.tsx
- frontend/components/base/data-table/cells/most-deleterious-consequence-cell.tsx
- frontend/components/base/data-table/cells/phenotype-condition-link-cell.tsx
- frontend/components/base/data-table/headers/table-tooltip-header.tsx
- frontend/components/base/navigation/phenotypes/phenotype-condition-link.tsx
- frontend/components/stories/table/cells-mock.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(table): SJRA-703 set new minSize and add aa_change

- frontend/apps/variant-entity/src/components/overview/prediction-scores-card.tsx
> fix(prediction): SJRA-708 reduce space for alert

- frontend/translations/common/fr.json
> fix(typo): SJRA-715 add fr translations

- frontend/components/feature/query-filters/numerical-filter.tsx
add documentation for numerical filter
> docs: sjra-629 add numerical filter documentation

- frontend/apps/case-entity/src/components/variants/occurrence-table/cells/interpretation-cell.tsx
- frontend/apps/case-entity/src/components/variants/occurrence-table/cells/occurence-actions-cell.tsx
- frontend/apps/case-entity/src/components/variants/occurrence-table/occurence-table-settings.tsx
- frontend/apps/case-entity/src/components/variants/occurrence-table/occurrence-expand.tsx
- frontend/components/stories/table/cells-mock.tsx
- frontend/components/stories/table/data-table-cells.stories.tsx
- frontend/components/stories/table/data-table.stories.tsx
- frontend/translations/common/en.json
- frontend/translations/common/fr.json
> feat(variant): SJRA-721 add menu actions

- frontend/apps/case-entity/src/components/variants/occurrence-table/cells/occurence-actions-cell.tsx
- frontend/components/base/buttons/action-button.tsx
> fix(action): SJRA-721 add missing icon and separator
